### ISSUE TITLE
关于该sim的使用

### ISSUE THREAD

**Issue by Ideasay** [rimimadision/OpenSSDSim#1]
hi，兄弟你好。我对这个OpenSSDSim很感兴趣。
请问有什么readme文件说明这个sim具体如何使用吗？谢谢你！

**Comment by rimimadision** [comment]
hello, 这个用于我们这边固件开发的功能验证框架，不知道你那边需要的是什么样子的，应该和你想做的寄存器模拟之类不太一样，因为只会给固件的驱动接口简单模拟一下

还有这个还不是正式的版本的，当时我可能不小心把这个仓库设置成了public的

**Comment by Ideasay** [comment]
> hello, 这个用于我们这边固件开发的功能验证框架，不知道你那边需要的是什么样子的，应该和你想做的寄存器模拟之类不太一样，因为只会给固件的驱动接口简单模拟一下
> 
> 还有这个还不是正式的版本的，当时我可能不小心把这个仓库设置成了public的
好好 谢谢你的回复！！
